# theme: jekyll-theme-slate

remote_theme: pages-themes/slate@v0.2.0
plugins:
- jekyll-remote-theme

markdown: kramdown

title: [Eche Mkpadi]
description: [Publish my digital interests]
url: [eche.com.ng]