# theme: jekyll-theme-slate

remote_theme: pages-themes/slate@v0.2.0
plugins:
  - jekyll-remote-theme

markdown: kramdown

title: Eche Mkpadi
description: Publish my digital interests
url: https://eche.com.ng

# Default Metadata for Open Graph and Twitter Card
defaults:
  - scope:
      path: ""
    values:
      description: "Explore articles about my digital interests."
      image: "/resources/work_setup.jpg"
